version: 0.2

env:
   parameter-store:
           DB_USER: "/ankur/db2user"
           DB_PASSWORD: "/ankur/db2pass"
           DB_HOST: "/ankur/db2host"
           DB_NAME: "/ankur/db2name"

phases:
    build:
        commands:
            - sed -i 's/dbname/'$DB_NAME'/' wp-config.php
            - sed -i 's/dbuser/'$DB_USER'/' wp-config.php
            - sed -i 's/dbpassword/'$DB_PASSWORD'/' wp-config.php
            - sed -i 's/dbhost/'$DB_HOST'/' wp-config.php

artifacts:
        files:
           - '**/*'